baseURL: https://example.org/
languageCode: en-us
title: Outside Context Solutions
theme:
  - paper-mod
  - hugo-shortcode-gallery
markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai
  goldmark:
    parser:
      attribute:
        block: true
        title: true
    renderer:
      unsafe: true
menu:
  main:
    # - weight: 25
    #   pre: "|"
    - identifier: design
      name: art & design
      url: /design/
      weight: 10
    - identifier: programming
      name: programming
      url: /programming/
      weight: 20
    - identifier: archive
      name: archive
      url: /archive/
      weight: 30
    - identifier: search
      name: search
      url: /search/
      weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  mainSections:
   - programming
   - design
   - misc
  TocOpen: true
  archive: true
  ShowCodeCopyButtons: true
  defaultTheme: auto
  ShowToc: false
  ShowReadingTime: true
  # assets:
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

